paesnodia= int(input("Digite o total de pães vendidos hoje: "))
broasnodia= int(input("Digite o total de broas vendidas hoje: "))
pz= float(0.38)
br= float(4.50)
pzv= float(paesnodia*pz)
brv= float(broasnodia*br)
totaldia= float(pzv+brv)
print(f"O total de pães vendidos foi: R$:{pzv}\nO total de broas vendidas hoje foi: R$:{brv}\nO total de vendas no dia foi: R$:{totaldia}")
poup= round((totaldia*10/100), 2)
print(f"O valor a ser guardado na poupança é de: R$: {poup}")