print("Os ganhadores do prémio de R$: 780.000,00 são: ")
nome = input("Digite o nome do primeiro ganhador: ")
pri = round((780000.0*46/100), 2)
print(f"O primeiro colocado foi o(a) {nome}, e ganhou R$: {pri}")
nome2 = input("Digite o nome do segundo ganhador: ")
seg = round((780000.0*32/100), 2)
print(f"O segundo colocado foi o(a) {nome2}, e ganhou R$: {seg}")
nome3 = input("Digite o nome do terciero ganhador: ")
ter = round((780000.0*22/100), 2)
print(f"O terceiro colocado foi o(a) {nome3}, e ganhou R$: {ter}")
